-- =============================================================
-- Universo seed: ~120 tickers más líquidos US
-- Ejecutar DESPUÉS de schema.sql
-- =============================================================

INSERT INTO universe (ticker, name, sector, indices) VALUES
-- Mega caps tech
('AAPL', 'Apple Inc.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('MSFT', 'Microsoft Corp.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('GOOGL', 'Alphabet Inc. Class A', 'Communication Services', ARRAY['SP500', 'NASDAQ100']),
('GOOG', 'Alphabet Inc. Class C', 'Communication Services', ARRAY['SP500', 'NASDAQ100']),
('AMZN', 'Amazon.com Inc.', 'Consumer Discretionary', ARRAY['SP500', 'NASDAQ100']),
('NVDA', 'NVIDIA Corp.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('META', 'Meta Platforms Inc.', 'Communication Services', ARRAY['SP500', 'NASDAQ100']),
('TSLA', 'Tesla Inc.', 'Consumer Discretionary', ARRAY['SP500', 'NASDAQ100']),
('AVGO', 'Broadcom Inc.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('ORCL', 'Oracle Corp.', 'Technology', ARRAY['SP500']),
-- Tech mid-large
('AMD', 'Advanced Micro Devices', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('CRM', 'Salesforce Inc.', 'Technology', ARRAY['SP500']),
('ADBE', 'Adobe Inc.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('CSCO', 'Cisco Systems Inc.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('INTC', 'Intel Corp.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('QCOM', 'QUALCOMM Inc.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('TXN', 'Texas Instruments', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('IBM', 'International Business Machines', 'Technology', ARRAY['SP500']),
('NOW', 'ServiceNow Inc.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('INTU', 'Intuit Inc.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('PLTR', 'Palantir Technologies', 'Technology', ARRAY['SP500']),
('PANW', 'Palo Alto Networks', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('SNOW', 'Snowflake Inc.', 'Technology', ARRAY['NASDAQ100']),
('SHOP', 'Shopify Inc.', 'Technology', ARRAY['NASDAQ100']),
('UBER', 'Uber Technologies', 'Industrials', ARRAY['SP500']),
('NFLX', 'Netflix Inc.', 'Communication Services', ARRAY['SP500', 'NASDAQ100']),
-- Semis
('TSM', 'Taiwan Semiconductor', 'Technology', ARRAY['SP500']),
('ASML', 'ASML Holding', 'Technology', ARRAY['NASDAQ100']),
('MU', 'Micron Technology', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('AMAT', 'Applied Materials', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('LRCX', 'Lam Research', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('KLAC', 'KLA Corp.', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('ARM', 'Arm Holdings', 'Technology', ARRAY['NASDAQ100']),
-- Financials
('JPM', 'JPMorgan Chase', 'Financials', ARRAY['SP500']),
('BAC', 'Bank of America', 'Financials', ARRAY['SP500']),
('WFC', 'Wells Fargo', 'Financials', ARRAY['SP500']),
('GS', 'Goldman Sachs', 'Financials', ARRAY['SP500']),
('MS', 'Morgan Stanley', 'Financials', ARRAY['SP500']),
('C', 'Citigroup', 'Financials', ARRAY['SP500']),
('BLK', 'BlackRock Inc.', 'Financials', ARRAY['SP500']),
('SCHW', 'Charles Schwab', 'Financials', ARRAY['SP500']),
('V', 'Visa Inc.', 'Financials', ARRAY['SP500']),
('MA', 'Mastercard Inc.', 'Financials', ARRAY['SP500']),
('AXP', 'American Express', 'Financials', ARRAY['SP500']),
('BRK.B', 'Berkshire Hathaway B', 'Financials', ARRAY['SP500']),
-- Healthcare
('UNH', 'UnitedHealth Group', 'Healthcare', ARRAY['SP500']),
('JNJ', 'Johnson & Johnson', 'Healthcare', ARRAY['SP500']),
('LLY', 'Eli Lilly', 'Healthcare', ARRAY['SP500']),
('ABBV', 'AbbVie Inc.', 'Healthcare', ARRAY['SP500']),
('PFE', 'Pfizer Inc.', 'Healthcare', ARRAY['SP500']),
('MRK', 'Merck & Co.', 'Healthcare', ARRAY['SP500']),
('TMO', 'Thermo Fisher', 'Healthcare', ARRAY['SP500']),
('ABT', 'Abbott Laboratories', 'Healthcare', ARRAY['SP500']),
('DHR', 'Danaher Corp.', 'Healthcare', ARRAY['SP500']),
('AMGN', 'Amgen Inc.', 'Healthcare', ARRAY['SP500', 'NASDAQ100']),
('GILD', 'Gilead Sciences', 'Healthcare', ARRAY['SP500', 'NASDAQ100']),
('CVS', 'CVS Health', 'Healthcare', ARRAY['SP500']),
-- Consumer
('WMT', 'Walmart Inc.', 'Consumer Staples', ARRAY['SP500']),
('COST', 'Costco Wholesale', 'Consumer Staples', ARRAY['SP500', 'NASDAQ100']),
('PG', 'Procter & Gamble', 'Consumer Staples', ARRAY['SP500']),
('KO', 'Coca-Cola', 'Consumer Staples', ARRAY['SP500']),
('PEP', 'PepsiCo Inc.', 'Consumer Staples', ARRAY['SP500', 'NASDAQ100']),
('MCD', 'McDonald''s Corp.', 'Consumer Discretionary', ARRAY['SP500']),
('SBUX', 'Starbucks Corp.', 'Consumer Discretionary', ARRAY['SP500', 'NASDAQ100']),
('NKE', 'Nike Inc.', 'Consumer Discretionary', ARRAY['SP500']),
('HD', 'Home Depot', 'Consumer Discretionary', ARRAY['SP500']),
('LOW', 'Lowe''s Companies', 'Consumer Discretionary', ARRAY['SP500']),
('TGT', 'Target Corp.', 'Consumer Staples', ARRAY['SP500']),
('DIS', 'Walt Disney Co.', 'Communication Services', ARRAY['SP500']),
-- Energy
('XOM', 'Exxon Mobil', 'Energy', ARRAY['SP500']),
('CVX', 'Chevron Corp.', 'Energy', ARRAY['SP500']),
('COP', 'ConocoPhillips', 'Energy', ARRAY['SP500']),
('SLB', 'Schlumberger', 'Energy', ARRAY['SP500']),
('EOG', 'EOG Resources', 'Energy', ARRAY['SP500']),
('OXY', 'Occidental Petroleum', 'Energy', ARRAY['SP500']),
-- Industrials
('CAT', 'Caterpillar Inc.', 'Industrials', ARRAY['SP500']),
('BA', 'Boeing Co.', 'Industrials', ARRAY['SP500']),
('GE', 'General Electric', 'Industrials', ARRAY['SP500']),
('HON', 'Honeywell Intl.', 'Industrials', ARRAY['SP500', 'NASDAQ100']),
('UPS', 'United Parcel Service', 'Industrials', ARRAY['SP500']),
('LMT', 'Lockheed Martin', 'Industrials', ARRAY['SP500']),
('RTX', 'RTX Corp.', 'Industrials', ARRAY['SP500']),
('DE', 'Deere & Co.', 'Industrials', ARRAY['SP500']),
-- Communication / Media
('VZ', 'Verizon Communications', 'Communication Services', ARRAY['SP500']),
('T', 'AT&T Inc.', 'Communication Services', ARRAY['SP500']),
('TMUS', 'T-Mobile US', 'Communication Services', ARRAY['SP500', 'NASDAQ100']),
('CMCSA', 'Comcast Corp.', 'Communication Services', ARRAY['SP500', 'NASDAQ100']),
-- Other
('LIN', 'Linde plc', 'Materials', ARRAY['SP500', 'NASDAQ100']),
('SPGI', 'S&P Global', 'Financials', ARRAY['SP500']),
('CB', 'Chubb Limited', 'Financials', ARRAY['SP500']),
('PYPL', 'PayPal Holdings', 'Financials', ARRAY['SP500', 'NASDAQ100']),
('SQ', 'Block Inc.', 'Financials', ARRAY['SP500']),
('COIN', 'Coinbase Global', 'Financials', ARRAY['SP500']),
('MSTR', 'MicroStrategy', 'Technology', ARRAY['NASDAQ100']),
('MARA', 'Marathon Digital', 'Technology', ARRAY[]::TEXT[]),
('RIOT', 'Riot Platforms', 'Technology', ARRAY[]::TEXT[]),
-- High volatility / movers (tradeables)
('SOFI', 'SoFi Technologies', 'Financials', ARRAY[]::TEXT[]),
('RIVN', 'Rivian Automotive', 'Consumer Discretionary', ARRAY['NASDAQ100']),
('LCID', 'Lucid Group', 'Consumer Discretionary', ARRAY['NASDAQ100']),
('PLTR', 'Palantir Technologies', 'Technology', ARRAY['SP500']),
('ROKU', 'Roku Inc.', 'Communication Services', ARRAY['NASDAQ100']),
('PINS', 'Pinterest Inc.', 'Communication Services', ARRAY['SP500']),
('SNAP', 'Snap Inc.', 'Communication Services', ARRAY[]::TEXT[]),
('SPOT', 'Spotify Technology', 'Communication Services', ARRAY['NASDAQ100']),
('ABNB', 'Airbnb Inc.', 'Consumer Discretionary', ARRAY['SP500', 'NASDAQ100']),
('DASH', 'DoorDash Inc.', 'Consumer Discretionary', ARRAY['NASDAQ100']),
('CRWD', 'CrowdStrike Holdings', 'Technology', ARRAY['SP500', 'NASDAQ100']),
('DDOG', 'Datadog Inc.', 'Technology', ARRAY['NASDAQ100']),
('ZS', 'Zscaler Inc.', 'Technology', ARRAY['NASDAQ100']),
('NET', 'Cloudflare Inc.', 'Technology', ARRAY[]::TEXT[]),
('MDB', 'MongoDB Inc.', 'Technology', ARRAY['SP500']),
('TEAM', 'Atlassian Corp.', 'Technology', ARRAY['NASDAQ100'])
ON CONFLICT (ticker) DO NOTHING;
